# Generated by Django 5.2.5 on 2025-09-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
