# Generated by Django 5.2.5 on 2025-10-01 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_cita_diagnostico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='diagnostico',
        ),
        migrations.AddField(
            model_name='receta',
            name='doctor',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='citas.doctor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receta',
            name='cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='citas.cita'),
        ),
    ]
