# Generated by Django 5.2.5 on 2025-10-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_remove_receta_diagnostico_receta_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='nuevo_diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
