# Generated by Django 5.2.5 on 2025-10-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_cita_nuevo_diagnostico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Atendida', 'Atendida')], default='Pendiente', max_length=50),
        ),
    ]
