# Generated by Django 5.2.5 on 2025-10-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID Chat Telegram'),
        ),
    ]
