# Generated by Django 5.2.5 on 2025-10-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_cita_telegram_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='telegram_chat_id',
        ),
        migrations.AddField(
            model_name='paciente',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID Chat Telegram'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
