# Generated by Django 5.2.5 on 2025-11-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_remove_cita_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='apellido',
            new_name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telegram_chat_id',
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='lugar_origen',
            field=models.CharField(default='Desconocido', max_length=150),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='primera_cita',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(default='Sin número', max_length=20),
        ),
    ]
