# Generated by Django 5.2.5 on 2025-11-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_alter_paciente_edad_alter_paciente_lugar_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='cedula_profesional',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
