# Generated by Django 5.2.5 on 2025-11-13 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0010_alter_doctor_cedula_profesional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='estudios/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('texto_extraido', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='citas.paciente')),
            ],
        ),
    ]
