# Generated by Django 5.2.5 on 2025-11-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0011_estudio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='nuevo_diagnostico',
            new_name='diagnostico_anterior',
        ),
    ]
