# Generated by Django 5.2.5 on 2025-11-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0012_rename_nuevo_diagnostico_cita_diagnostico_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='nuevo_diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
