# Generated by Django 5.2.5 on 2025-11-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0014_diagnosticohistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='instrucciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='medicamentos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
