# Generated by Django 5.2.5 on 2025-12-08 03:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0015_cita_instrucciones_cita_medicamentos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-fecha', '-hora']},
        ),
        migrations.AlterModelOptions(
            name='estudio',
            options={'ordering': ['-fecha_subida']},
        ),
        migrations.AddField(
            model_name='doctor',
            name='horario_consulta',
            field=models.CharField(default='Lunes a Viernes de 9:00 a.m - 4:00 p.m', max_length=100, verbose_name='Horario de consulta'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(default=5, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener exactamente 10 dígitos.', regex='^\\d{10}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signos', to='citas.cita'),
        ),
    ]
