# Generated by Django 5.2.5 on 2025-12-09 20:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0016_alter_cita_options_alter_estudio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={},
        ),
        migrations.AlterModelOptions(
            name='estudio',
            options={},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='horario_consulta',
        ),
        migrations.AddField(
            model_name='doctor',
            name='horario',
            field=models.CharField(default='Lunes a Viernes de 9:00 a.m - 4:00 p.m', max_length=150, verbose_name='Horario de Consulta'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citas.cita'),
        ),
    ]
